### ISSUE TITLE
If Nydus Snapshotter goes down, the containerd can still be downgraded to pulling normal OCI images?

### ISSUE THREAD

**Issue by xianlubird** [dragonflyoss/nydus#1546]
If Nydus Snapshotter goes down, the containerd can still be downgraded to pulling normal OCI images?

**Comment by imeoer** [comment]
Currently containerd does not have a snapshotter fallback mechanism, so containers that use nydus images cannot be created when the nydus snapshotter does not work.

It is recommended that adding a health check to the nydus snapshotter, so that if the node's snapshotter goes down, scheduling to this node should be avoided.
